Lab_TDD/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
import status.urls as status

urlpatterns = [
	url(r'^', include(('status.urls','status'), namespace='status')),
	url(r'^auth/', include('social_django.urls', namespace='social')),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

status/urls.py
from django.conf.urls import url
from django.urls import re_path,include
from .views import index,add_status, index_2, index_json, data_json, index_subscribe, add_subscriber, validate_email, index_login, logout_view
from . import views

urlpatterns = [
    url(r'^$', index, name='index'),
    url('myprofile/', index_2, name='index_2'),
    url('add_status/', add_status, name = 'add_status'),
	url('data_json/', data_json, name = 'data_json'),
	url('books/', index_json, name = 'book'),
	url('validate_email/', validate_email, name = 'validate_email'),
	url('registration/', index_subscribe, name='index_subscribe'),
	url('add_subscriber/', add_subscriber, name = 'add_subscriber'),
	url('loginform/', index_login, name = 'loginform'),
	url('logout/', logout_view , name = 'logout'),

	
	
]

status/models.py
from django.db import models
from datetime import datetime, date
from django.core.validators import MinLengthValidator

# Create your models here.
class Status(models.Model):
	date = models.DateTimeField(default = datetime.now())
	status = models.TextField(max_length = 300)

class Subscribe(models.Model):
	email = models.EmailField(error_messages={'unique': 'An account with this email exist.'})
	nama = models.CharField(max_length = 50)
	password = models.CharField(validators=[MinLengthValidator(4)], max_length = 20)

status/forms.py
from django import forms
from .models import Status,Subscribe
from django.forms import ModelForm

class Status_Form(forms.ModelForm):
	status_attrs = {
		'id' : 'status',
		'type': 'text',
		'class': 'form-control',
		'placeholder':'Type your status here..'
	}
	status = forms.CharField(label='Status', required = True, widget=forms.TextInput(attrs=status_attrs))

	class Meta :
		model = Status
		fields = ('status',)
		
class Subscribe_Form(forms.ModelForm):
	nama_attrs = {
		'id' : 'id_nama',
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Name'
    }
	email_attrs = {
		'id' : 'id_email',
        'type': 'email',
        'class': 'form-control',
        'placeholder':'Email'
    }
	pass_attrs = {
		'id' : 'id_password',
        'type': 'password',
        'class': 'form-control',
        'placeholder':'Password',
		'required pattern' : '[a-zA-Z0-9]+',
		'title' : 'Harus Alpha Numeric'
    }
	email = forms.EmailField(widget=forms.TextInput(attrs=email_attrs))
	nama = forms.CharField(widget=forms.TextInput(attrs=nama_attrs))
	password = forms.CharField(min_length = 8 ,widget=forms.TextInput(attrs=pass_attrs))
	class Meta :
		model = Subscribe
		fields = ('email','nama', 'password',)

status/views.py
from django.shortcuts import render, redirect
from .models import Status, Subscribe
from datetime import datetime
from .forms import Status_Form, Subscribe_Form
from . import forms
from django.http import HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse
import requests

response = {}
def index(request):
	response['form'] = forms.Status_Form
	response['status'] = Status.objects.all()
	html = 'lab_6.html'
	return render(request, html, response)

def index_2(request):
    return render(request, 'my_profile.html')

def add_status(request):
	form = forms.Status_Form(request.POST)
	if form.is_valid():
		response['status'] = request.POST['status']
		status = Status(status = response['status'])
		status.save()
		return HttpResponseRedirect('/')
	else:
		form = forms.Status_Form()

	return render(request, 'lab_6.html', response)
	
@csrf_exempt	
def add_subscriber(request):
	response = {}
	if (request.method == "POST" or None):
		response['email'] = request.POST['email']
		response['nama'] = request.POST['nama']
		response['password'] = request.POST['password']
		subscriber = Subscribe(email = response['email'], nama = response['nama'], password = response['password'])
		subscriber.save()
	return JsonResponse({})
	
def index_json(request):
	return render(request, 'book.html')
	
def data_json(request):
	search = "https://www.googleapis.com/books/v1/volumes?q=quilting" 
	my_list = requests.get(search)
	json = my_list.json()
	return JsonResponse(json)
	
def index_login(request):
	return render(request, 'login.html')
	
def index_subscribe(request):
	forms = Subscribe.objects.all()
	response = {'form' : Subscribe_Form, 'result': forms}
	return render(request, "subscribe.html", response)

@csrf_exempt	
def validate_email(request):
	email = request.POST.get('email', None)
	data = {
		'is_taken': Subscribe.objects.filter(email=email).exists()
	}
	return JsonResponse(data)

def my_view(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(request, username = username, password = password)
	if user is not None:
		request.session['user_login'] = username
		res =  HttpResponseRedirect('status:book')
		res.set_cookie('test', 'berhasil')
		res.set_cookie('username', username)
	else:
		return HttpResponseRedirect('/loginform')
		
def logout_view(request):
	logout(request)
	return HttpResponseRedirect('/books')
	

status/templates/book.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title> BOOK </title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'myscripts.js'%}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
</head> 

<body>
    <div class = "preloader">
        <img src = "{% static 'spinner.gif' %}">
    </div>

    <div class = "mycontent">
        <div class="jumbotron">
            <h2 style="font-size:300%; text-align: center">My Book</h2>
        </div>
        {% if user.is_authenticated %}
            <h2 style="font-size : 30px;text-align: center" > Welcome, {{ user.first_name }} {{user.last_name}} !</h2><br>
        {% endif %}

        <div class = "btngrup" style = "text-align: center">
            <button type="button" class="btn btn-info" onclick="window.location.href='/myprofile'"> My Profile </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/registration'">Registration </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/'"> Status </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/books'"> Books </button>
        </div>

        <div class = "container">
            {% if user.is_authenticated %}
                <a type="button" class="btn btn-danger" href="{% url 'status:logout' %}">Logout</a>
            {% else %}
                <a type="button" class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">Log in with Google</a>
            {% endif %}
        </div>

        <div class = "container">
            <h2 id= "jumlahBuku" style = "text-align: center">
                <i class='fa fa-star'style = 'color : yellow'> </i> 0 
            </h2>

            <form>
                <input type="text" name="search_field">
            </form>

            <br>

            <table class = "table-responsive table table-stripped" id = "tableBuku"> 
            </table>
        </div>
    </div>

</body>
</html>
    

status/templates/lab_6.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Status</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="YOUR_CLIENT_ID.apps.googleusercontent.com">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="{% static 'myscripts.js'%}"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
</head>

<body>
    <div class = "preloader">
        <img src = "{% static 'spinner.gif' %}">
    </div>

    <div class = "mycontent">
        <div class="jumbotron">
            <h2 style="font-size : 50px; text-align: center" > Hello, Apa kabar? </h2>
        </div>
        <div class = "btngrup" style = "text-align: center">
            <button type="button" class="btn btn-info" onclick="window.location.href='/myprofile'"> My Profile </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/registration'">Registration </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/'"> Status </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/books'"> Books </button>
        </div>

        <div class = "container">
            {% if user.is_authenticated %}
                <a type="button" class="btn btn-danger" href="{% url 'status:logout' %}">Logout</a>
            {% else %}
                <a type="button" class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">Log in with Google</a>
            {% endif %}
        </div>
        <br>
        <section>
            <div class="row">
                <div class = "col-md-3">
                </div>
                <div class="col-md-6 col-md-offset-6">
                    <div class="form-regis">
                        <form id="form" method="POST" action = "{% url 'status:add_status' %}">
                            {% csrf_token %}
                            {{form}}
                            <br>
                            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                            <br>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <div class = "container">
            <div class="table-responsive">
                {% if status %}
                <table class = "table table-hover">
                    <thead>
                        <th> Status </th>
                        <th> Date </th>
                    </thead>
                    {% for data in status %}
                    <tr>
                        <td> {{ data.status }} </td>
                        <td> {{ data.date }} </td>
                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                <h2> No Status </h2>
                {% endif %}
            </div> 
        </div> 
    </div>   
</body>
</html>

status/templates/login.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="{% static 'myscripts.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
</head>

<body>
    <div class = "preloader">
        <img src = "{% static 'spinner.gif' %}">
    </div>

    <div class = "mycontent">
        <div class="jumbotron">
            <h1 style="font-size : 50px" > Hello, Apa kabar? </h1>
        </div>
        <div class = "btngrup" style = "text-align: center">
            <button type="button" class="btn btn-info" onclick="window.location.href='/myprofile'"> My Profile </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/registration'">Registration </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/'"> Status </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/books'"> Books </button>
        </div>
        <br>
        <section>
            <div class="row">
                <div class = "col-md-3">
                </div>
                <div class="col-md-6 col-md-offset-6">
                    <div class="form-regis">
                        <form id="form" method="POST" action = "{% url 'status:login' %}">
                            {% csrf_token %}
                            Username:<br>
                            <input type="text" name="username"><br>
                            Password:<br>
                            <input type="password" name="password"><br><br>
                            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                            <br>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>   
</body>
</html>

status/templates/my_profile.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>I Made Adisurya Nugraha</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'myscripts.js'%}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
</head> 

<body>
    <div class = "preloader">
        <img src = "{% static 'spinner.gif' %}">
    </div>

    <div class = "mycontent">
        <div class="jumbotron">
            <img src= "{% static 'foto.jpg' %}">
            <h2 style="font-size:300%; text-align: center">I Made Adisurya Nugraha</h2>
        </div>
        <div class = "btngrup" style = "text-align: center">
            <button type="button" class="btn btn-info" onclick="window.location.href='/myprofile'"> My Profile </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/registration'">Registration </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/'"> Status </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/books'"> Books </button>
        </div>

        <div class = "container">
            {% if user.is_authenticated %}
                <a type="button" class="btn btn-danger" href="{% url 'status:logout' %}">Logout</a>
            {% else %}
                <a type="button" class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">Log in with Google</a>
            {% endif %}
        </div>
        <br>
    
        <div class = "container">
            <button type="button" class="btn btn-info" id = "ubahbutton"> Ubah Tema!</button> <br>

            <h1 id = "flip" style="font-size : 20px"> About Me </h1>
            <div id= "panel">
                <p style="text-align :center"> Hello, my name is I Made Adisurya Nugraha. I am an Information System student in Faculty
                of Computer Science, University of Indonesia. Now i am in the third term of my college. 
                In this term, i have to study about web programming called "PPW". Now i am struggling so 
                hard to try make this web, because i never learned about design and web programming
                before. I hope i could finished this subject and get the best score. Wish me luck !
                </p>
            </div>
    
            <h1 id = "flip2" style="font-size : 20px"> Experience </h1>
            <div id = "panel2">
                <ul>
                    <br>
                    <li>Anggota MPK SMAN 3 Depok</li>
                    <li>PO Coss Camp SMAN 3 Depok</li>  
                    <li>VPO UI Goes to School</li> 
                    <li>Staff Seminar COMPFEST X</li>
                    <li>PO KMHD Art Competition 2018</li>
                    <br>
                </ul>
            </div>
    
            <h1 id = "flip3" style="font-size : 20px"> Achievement </h1>
            <div id = "panel3">
                <ul>
                    <br>
                    <li>Finalis National Logic Competition 2016</li>
                    <li>Olimpiade Sains Kota Matematika 2015 2016</li>  
                    <li>40 Besar Pesta Sains Nasional bidang Matematika</li> 
                    <li>Penyisihan 2 lomba matematika LOGIKA 2016</li>
                    <br> 
                </ul>
            </div>
    
        </div>
    </div>

</body>
</html>
    

status/templates/subscribe.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Registration</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'myscripts.js'%}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
</head> 

<body>
    <div class = "preloader">
        <img src = "{% static 'spinner.gif' %}">
    </div>

    <div class = "mycontent">
        <div class="jumbotron">
            <h2 style="font-size:300%; text-align: center">Subscribe Registration</h2>
        </div>

        <div class = "btngrup" style = "text-align: center">
            <button type="button" class="btn btn-info" onclick="window.location.href='/myprofile'"> My Profile </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/registration'">Registration </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/'"> Status </button>
            <button type="button" class="btn btn-info" onclick="window.location.href='/books'"> Books </button>
        </div>

        <div class = "container">
            {% if user.is_authenticated %}
                <a type="button" class="btn btn-danger" href="{% url 'status:logout' %}">Logout</a>
            {% else %}
                <a type="button" class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">Log in with Google</a>
            {% endif %}
        </div>
        
        <section>
            <div class="row">
                <div class = "col-md-3">
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="form-regis">
                        <form id="form" method="POST">
                            <br><br>
                            {% csrf_token %}
                            {{form}}
                            <br>
                            <input id="submit_regis" type="submit" onclick="submit_post()" class="btn btn-lg btn-block btn-info" data-toggle="modal" data-target="#myModal" disabled>
                            <br>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <div class="container">
            <div class="modal" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">SUKSES !</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
    
                        <!-- Modal body -->
                        <div class="modal-body">
                            Data anda berhasil tersimpan ...
                        </div>
    
                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
                        </div>
    
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>
    